# Generated by Django 4.1.5 on 2023-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_seance', '0001_initial'),
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('module', models.ManyToManyField(blank=True, to='app_module.module')),
                ('seances', models.ManyToManyField(blank=True, to='app_seance.seance')),
            ],
        ),
    ]
