# Generated by Django 4.1.5 on 2023-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_module', '0001_initial'),
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('module', models.ManyToManyField(to='app_module.module')),
                ('seances', models.ManyToManyField(to='app_seance.seance')),
            ],
        ),
    ]
