# Generated by Django 4.1.5 on 2023-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('numero', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
