# Generated by Django 4.1.5 on 2023-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('numero', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('seances', models.ManyToManyField(to='app_seance.seance')),
            ],
        ),
    ]
