# Generated by Django 4.1.5 on 2023-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.CharField(max_length=4),
        ),
    ]
