# Generated by Django 4.1.5 on 2023-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salle', '0002_remove_salle_seances'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
