# Generated by Django 4.1.5 on 2023-02-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nb_heures', models.IntegerField()),
                ('seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_seance.seance')),
            ],
        ),
    ]
