# Generated by Django 4.1.5 on 2023-02-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nb_heures', models.DecimalField(decimal_places=1, max_digits=4)),
                ('seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_seance.seance')),
            ],
        ),
    ]
