# Generated by Django 4.1.5 on 2023-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nb_heures', models.IntegerField()),
            ],
        ),
    ]
