# Generated by Django 4.1.5 on 2023-03-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0003_remove_module_cours'),
        ('app_cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='app_module.module'),
        ),
    ]
