# Generated by Django 4.1.5 on 2023-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='effectif',
            field=models.TextField(choices=[('1/2 Promo', '1/2 Promo'), ('Promo complète', 'Promo complète'), ('Groupe de TP', 'Groupe de TP'), ('1/2 Groupe de TP', '1/2 Groupe de TP'), ('Groupe de TD', 'Groupe de TD'), ('1/2 Groupe de TD', '1/2 Groupe de TD')], null=True),
        ),
    ]
