# Generated by Django 4.1.5 on 2023-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='type',
            field=models.TextField(choices=[('CM', 'CM'), ('CI', 'CI'), ('TD', 'TD'), ('TP', 'TP'), ('BE', 'BE'), ('AUTONOMIE', 'AUTONOMIE')], default='CM'),
            preserve_default=False,
        ),
    ]
