# Generated by Django 4.1.5 on 2023-06-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0002_remove_module_enseignant_module_coordonnateur1_and_more'),
        ('app_cours', '0002_cours_effectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='app_module.module'),
        ),
    ]
