# Generated by Django 4.1.5 on 2023-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0003_alter_cours_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='nb_heures_autonomie',
            new_name='nb_heures_hors_presentiel',
        ),
        migrations.AlterField(
            model_name='cours',
            name='type',
            field=models.TextField(choices=[('CM', 'CM'), ('CI', 'CI'), ('TD', 'TD'), ('TP', 'TP'), ('BE', 'BE'), ('Hors Présentiel', 'Hors Présentiel')]),
        ),
    ]
