# Generated by Django 4.1.5 on 2023-04-27 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0004_rename_nb_heures_autonomie_cours_nb_heures_hors_presentiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='nb_heures',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nb_heures_hors_presentiel',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
