# Generated by Django 4.1.5 on 2023-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0005_remove_cours_seances'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='nb_heures_autonomie',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
