# Generated by Django 4.1.5 on 2023-04-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0005_alter_cours_nb_heures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='type',
            field=models.TextField(choices=[('CM', 'CM'), ('CI', 'CI'), ('TD', 'TD'), ('TP', 'TP'), ('BE', 'BE')]),
        ),
    ]
