# Generated by Django 4.1.5 on 2023-02-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cours', '0001_initial'),
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('nb_heures_total', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nb_heures_tp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nb_heures_be', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nb_heures_ci', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='app_cours.cours')),
                ('seances', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='app_seance.seance')),
            ],
        ),
    ]
