# Generated by Django 4.1.5 on 2023-02-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('nb_heures_total', models.IntegerField()),
                ('nb_heures_tp', models.IntegerField()),
                ('nb_heures_be', models.IntegerField()),
                ('nb_heures_ci', models.IntegerField()),
            ],
        ),
    ]
