# Generated by Django 4.1.5 on 2023-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='nb_heures_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='nb_heures_td',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
