# Generated by Django 4.1.5 on 2023-04-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignant', '0001_initial'),
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='app_enseignant.enseignant'),
        ),
    ]
