# Generated by Django 4.1.5 on 2023-05-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignant', '0001_initial'),
        ('app_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='module',
            name='coordonnateur1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_coordonnateur1', to='app_enseignant.enseignant'),
        ),
        migrations.AddField(
            model_name='module',
            name='coordonnateur2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_coordonnateur2', to='app_enseignant.enseignant'),
        ),
    ]
