# Generated by Django 4.1.5 on 2023-03-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0002_module_nb_heures_cm_module_nb_heures_td'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
    ]
