# Generated by Django 4.1.5 on 2023-04-27 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0003_alter_module_nb_heures_be_alter_module_nb_heures_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='nb_heures_hors_presentiel',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
