# Generated by Django 4.1.5 on 2023-03-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0005_remove_module_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='seances',
        ),
    ]
