# Generated by Django 4.1.5 on 2023-03-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignant', '0003_remove_enseignant_module_remove_enseignant_seances'),
        ('app_module', '0006_remove_module_seances'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='app_enseignant.enseignant'),
        ),
    ]
