# Generated by Django 4.1.5 on 2023-04-27 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_enseignant', '0001_initial'),
        ('app_module', '0001_initial'),
        ('app_cours', '0001_initial'),
        ('app_salle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=15)),
                ('heure_debut', models.CharField(max_length=15)),
                ('heure_fin', models.CharField(max_length=15)),
                ('effectif', models.TextField(choices=[('1/2 Promo', '1/2 Promo'), ('Promo complète', 'Promo complète'), ('Groupe de TP', 'Groupe de TP'), ('1/2 Groupe de TP', '1/2 Groupe de TP'), ('Groupe de TD', 'Groupe de TD'), ('1/2 Groupe de TD', '1/2 Groupe de TD')], null=True)),
                ('commentaire', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_groupe_td', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_cours.cours')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance', to='app_enseignant.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_module.module')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance', to='app_salle.salle')),
            ],
        ),
    ]
