# Generated by Django 4.1.5 on 2023-05-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='effectif',
        ),
    ]
