# Generated by Django 4.1.5 on 2023-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
