# Generated by Django 4.1.5 on 2023-03-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cours', '0005_remove_cours_seances'),
        ('app_module', '0006_remove_module_seances'),
        ('app_seance', '0002_alter_seance_date_debut_alter_seance_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='app_cours.cours'),
        ),
        migrations.AddField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='app_module.module'),
        ),
    ]
