# Generated by Django 4.1.5 on 2023-03-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignant', '0003_remove_enseignant_module_remove_enseignant_seances'),
        ('app_cours', '0005_remove_cours_seances'),
        ('app_module', '0007_module_enseignant'),
        ('app_seance', '0003_seance_cours_seance_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_enseignant.enseignant'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_cours.cours'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_module.module'),
        ),
    ]
