# Generated by Django 4.1.5 on 2023-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0004_alter_seance_cours_alter_seance_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='effectif',
            field=models.TextField(choices=[('1/2 Promo', '1/2 Promo'), ('Promo complète', 'Promo complète'), ('Groupe de TP', 'Groupe de TP'), ('1/2 Groupe de TP', '1/2 Groupe de TP'), ('Groupe de TD', 'Groupe de TD'), ('1/2 Groupe de TD', '1/2 Groupe de TD')], null=True),
        ),
    ]
