# Generated by Django 4.1.5 on 2023-03-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_salle', '0002_remove_salle_seances'),
        ('app_seance', '0004_seance_enseignant_alter_seance_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_salle.salle'),
        ),
    ]
