# Generated by Django 4.1.5 on 2023-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0005_alter_seance_effectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='numero_groupe_td',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
    ]
