# Generated by Django 4.1.5 on 2023-03-30 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0005_seance_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
