# Generated by Django 4.1.5 on 2023-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0006_remove_seance_date_debut_remove_seance_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='commentaire',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seance',
            name='effectif',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
