# Generated by Django 4.1.5 on 2023-04-08 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seance', '0007_alter_seance_numero_groupe_td'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='numero_groupe_td',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
