# Generated by Django 4.1.5 on 2023-04-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0002_alter_module_enseignant'),
        ('app_cours', '0004_rename_nb_heures_autonomie_cours_nb_heures_hors_presentiel_and_more'),
        ('app_seance', '0008_alter_seance_numero_groupe_td'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_cours.cours'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='app_module.module'),
        ),
    ]
